--liquibase formatted sql
drop table if exists cinema_halls;
drop table if exists movie_sessions;
drop table if exists movies;
drop table if exists orders;
drop table if exists orders_tickets;
drop table if exists shopping_carts;
drop table if exists shopping_carts_tickets;
drop table if exists tickets;
drop table if exists users;
create table cinema_halls (id bigint not null auto_increment, capacity integer not null, description varchar(255), primary key (id)) engine=InnoDB;
create table movie_sessions (id bigint not null auto_increment, show_time datetime, cinema_hall_id bigint, movie_id bigint, primary key (id)) engine=InnoDB;
create table movies (id bigint not null auto_increment, description varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table orders (id bigint not null, orderDate datetime, primary key (id)) engine=InnoDB;
create table orders_tickets (ticket_id bigint not null, order_id bigint not null) engine=InnoDB;
create table shopping_carts (id bigint not null, primary key (id)) engine=InnoDB;
create table shopping_carts_tickets (shopping_cart_id bigint not null, ticket_id bigint not null) engine=InnoDB;
create table tickets (id bigint not null auto_increment, movie_session_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), password varchar(255), salt tinyblob, primary key (id)) engine=InnoDB;
alter table orders_tickets add constraint UK_mrm4coh6ry9h4s0qka8x5sqg6 unique (order_id);
alter table shopping_carts_tickets add constraint UK_eusu1u2g6d73fcjvox629ct9y unique (ticket_id);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table movie_sessions add constraint FKfqu527x0e0675k7vkm21ghv08 foreign key (cinema_hall_id) references cinema_halls (id);
alter table movie_sessions add constraint FKatpmn0h31nwhwdgd0ogr8q6kj foreign key (movie_id) references movies (id);
alter table orders add constraint FKlt6imiaaf9u67mf9aqfbs48od foreign key (id) references users (id);
alter table orders_tickets add constraint FKta90cc5ym65a1000smtyf99pf foreign key (order_id) references tickets (id);
alter table orders_tickets add constraint FKfwm4r3tihmyfnosq423lomr0i foreign key (ticket_id) references orders (id);
alter table shopping_carts add constraint FKc1fbrvff059ke4p8ce3hu38oa foreign key (id) references users (id);
alter table shopping_carts_tickets add constraint FKaw8rn6oivawiyro857w06we16 foreign key (ticket_id) references tickets (id);
alter table shopping_carts_tickets add constraint FKm5n3i4h3nk1p1yqywkn1kpej6 foreign key (shopping_cart_id) references shopping_carts (id);
alter table tickets add constraint FKidxabarcn97kf9acrcqokf1r9 foreign key (movie_session_id) references movie_sessions (id);
alter table tickets add constraint FK4eqsebpimnjen0q46ja6fl2hl foreign key (user_id) references users (id);